<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup Label="feature">
		<Authors>dit-zy</Authors>
		<Title>Ditzy Extensions // Testing</Title>
		<Version>1.0.0-SNAPSHOT-0</Version>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<Description>a collection of extensions and utilities for writing fluent and property based unit tests.</Description>
		<RepositoryUrl>https://github.com/dit-zy/ditzy-extensions</RepositoryUrl>
		<TargetFrameworks>net9.0;net8.0;net7.0;net6.0;net48;netstandard2.0</TargetFrameworks>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>
	
	<PropertyGroup Condition=" '$(TargetFramework)' != 'net48' And '$(TargetFramework)' != 'netstandard2.0' ">
		<Nullable>enable</Nullable>
		<LangVersion>12.0</LangVersion>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(TargetFramework)' == 'net48' Or '$(TargetFramework)' == 'netstandard2.0' ">
		<DefineConstants>N48_S2</DefineConstants>
	</PropertyGroup>
	
	<ItemGroup>
		<ProjectReference Include="../DitzyExtensions/DitzyExtensions.csproj"/>
		<ProjectReference
			Include="..\DitzyExtensions.Testing.Generators\DitzyExtensions.Testing.Generators.csproj"
			OutputItemType="Analyzer"
			ReferenceOutputAssembly="false"
		/>
	</ItemGroup>

	<ItemGroup Label="dependencies">
		<PackageReference Include="CSharpFunctionalExtensions" Version="3.6.0" />
		<PackageReference Include="FluentAssertions" Version="8.2.0" />
		<PackageReference Include="FsCheck" Version="3.2.0" />
		<PackageReference Include="FsCheck.Xunit" Version="3.2.0" />
	</ItemGroup>
</Project>
