//HintName: VectorExtensions.g.cs
// <autogenerated/>
using System.Numerics;

namespace GenTests.Tests {
	public static partial class VectorExtensions {
	
		public static Vector3 XYZ(this Vector4 source) =>
			new Vector3(source.X, source.Y, source.Z);
		public static Vector3 XYW(this Vector4 source) =>
			new Vector3(source.X, source.Y, source.W);
		public static Vector3 XZY(this Vector4 source) =>
			new Vector3(source.X, source.Z, source.Y);
		public static Vector3 XZW(this Vector4 source) =>
			new Vector3(source.X, source.Z, source.W);
		public static Vector3 XWY(this Vector4 source) =>
			new Vector3(source.X, source.W, source.Y);
		public static Vector3 XWZ(this Vector4 source) =>
			new Vector3(source.X, source.W, source.Z);
		public static Vector3 YXZ(this Vector4 source) =>
			new Vector3(source.Y, source.X, source.Z);
		public static Vector3 YXW(this Vector4 source) =>
			new Vector3(source.Y, source.X, source.W);
		public static Vector3 YZX(this Vector4 source) =>
			new Vector3(source.Y, source.Z, source.X);
		public static Vector3 YZW(this Vector4 source) =>
			new Vector3(source.Y, source.Z, source.W);
		public static Vector3 YWX(this Vector4 source) =>
			new Vector3(source.Y, source.W, source.X);
		public static Vector3 YWZ(this Vector4 source) =>
			new Vector3(source.Y, source.W, source.Z);
		public static Vector3 ZXY(this Vector4 source) =>
			new Vector3(source.Z, source.X, source.Y);
		public static Vector3 ZXW(this Vector4 source) =>
			new Vector3(source.Z, source.X, source.W);
		public static Vector3 ZYX(this Vector4 source) =>
			new Vector3(source.Z, source.Y, source.X);
		public static Vector3 ZYW(this Vector4 source) =>
			new Vector3(source.Z, source.Y, source.W);
		public static Vector3 ZWX(this Vector4 source) =>
			new Vector3(source.Z, source.W, source.X);
		public static Vector3 ZWY(this Vector4 source) =>
			new Vector3(source.Z, source.W, source.Y);
		public static Vector3 WXY(this Vector4 source) =>
			new Vector3(source.W, source.X, source.Y);
		public static Vector3 WXZ(this Vector4 source) =>
			new Vector3(source.W, source.X, source.Z);
		public static Vector3 WYX(this Vector4 source) =>
			new Vector3(source.W, source.Y, source.X);
		public static Vector3 WYZ(this Vector4 source) =>
			new Vector3(source.W, source.Y, source.Z);
		public static Vector3 WZX(this Vector4 source) =>
			new Vector3(source.W, source.Z, source.X);
		public static Vector3 WZY(this Vector4 source) =>
			new Vector3(source.W, source.Z, source.Y);
	}
}
