//HintName: VectorExtensions.g.cs
// <autogenerated/>
using System.Numerics;

namespace GenTests.Tests {
	public static partial class VectorExtensions {
	
		public static Vector4 XYZW(this Vector4 source) =>
			new Vector4(source.X, source.Y, source.Z, source.W);
		public static Vector4 XYWZ(this Vector4 source) =>
			new Vector4(source.X, source.Y, source.W, source.Z);
		public static Vector4 XZYW(this Vector4 source) =>
			new Vector4(source.X, source.Z, source.Y, source.W);
		public static Vector4 XZWY(this Vector4 source) =>
			new Vector4(source.X, source.Z, source.W, source.Y);
		public static Vector4 XWYZ(this Vector4 source) =>
			new Vector4(source.X, source.W, source.Y, source.Z);
		public static Vector4 XWZY(this Vector4 source) =>
			new Vector4(source.X, source.W, source.Z, source.Y);
		public static Vector4 YXZW(this Vector4 source) =>
			new Vector4(source.Y, source.X, source.Z, source.W);
		public static Vector4 YXWZ(this Vector4 source) =>
			new Vector4(source.Y, source.X, source.W, source.Z);
		public static Vector4 YZXW(this Vector4 source) =>
			new Vector4(source.Y, source.Z, source.X, source.W);
		public static Vector4 YZWX(this Vector4 source) =>
			new Vector4(source.Y, source.Z, source.W, source.X);
		public static Vector4 YWXZ(this Vector4 source) =>
			new Vector4(source.Y, source.W, source.X, source.Z);
		public static Vector4 YWZX(this Vector4 source) =>
			new Vector4(source.Y, source.W, source.Z, source.X);
		public static Vector4 ZXYW(this Vector4 source) =>
			new Vector4(source.Z, source.X, source.Y, source.W);
		public static Vector4 ZXWY(this Vector4 source) =>
			new Vector4(source.Z, source.X, source.W, source.Y);
		public static Vector4 ZYXW(this Vector4 source) =>
			new Vector4(source.Z, source.Y, source.X, source.W);
		public static Vector4 ZYWX(this Vector4 source) =>
			new Vector4(source.Z, source.Y, source.W, source.X);
		public static Vector4 ZWXY(this Vector4 source) =>
			new Vector4(source.Z, source.W, source.X, source.Y);
		public static Vector4 ZWYX(this Vector4 source) =>
			new Vector4(source.Z, source.W, source.Y, source.X);
		public static Vector4 WXYZ(this Vector4 source) =>
			new Vector4(source.W, source.X, source.Y, source.Z);
		public static Vector4 WXZY(this Vector4 source) =>
			new Vector4(source.W, source.X, source.Z, source.Y);
		public static Vector4 WYXZ(this Vector4 source) =>
			new Vector4(source.W, source.Y, source.X, source.Z);
		public static Vector4 WYZX(this Vector4 source) =>
			new Vector4(source.W, source.Y, source.Z, source.X);
		public static Vector4 WZXY(this Vector4 source) =>
			new Vector4(source.W, source.Z, source.X, source.Y);
		public static Vector4 WZYX(this Vector4 source) =>
			new Vector4(source.W, source.Z, source.Y, source.X);
	}
}
