//HintName: SwizzleAttribute.g.cs
// <autogenerated/>
using System;

namespace DitzyExtensions.Generators {
	[AttributeUsage(AttributeTargets.Class, AllowMultiple=true, Inherited=false)]
	public class SwizzleAttribute : System.Attribute {

		public Type SourceClass { get; set; }
		public Type TargetClass { get; set; } = null;
		public int NumComponentsToChoose { get; set; } = 0;
		public string[] ComponentsToSwizzle { get; set; }
		
		public SwizzleAttribute() :
			this(null) {}

		public SwizzleAttribute(Type sourceClass, params string[] componentsToSwizzle) :
			this(sourceClass, null, 0, componentsToSwizzle) {}

		public SwizzleAttribute(Type sourceClass, Type targetClass, params string[] componentsToSwizzle) :
			this(sourceClass, targetClass, componentsToSwizzle.Length, componentsToSwizzle) {}
		
		public SwizzleAttribute(Type sourceClass, Type targetClass, int numComponentsToChoose, params string[] componentsToSwizzle) {
			SourceClass = sourceClass;
			TargetClass = targetClass;
			NumComponentsToChoose = numComponentsToChoose;
			ComponentsToSwizzle = componentsToSwizzle;
		}
	}
}