using System.Collections.Immutable;
using System.Text;

namespace DitzyExtensions.Generators;

public class GenUtils {
	public const string SwizzleAttributeFqn = "DitzyExtensions.Generators.SwizzleAttribute";
	public const string GenNamespace = "DitzyExtensions.Generators";

	public const string Swizzle = $$"""
		// <autogenerated/>
		using System;

		namespace {{GenNamespace}} {
			[AttributeUsage(AttributeTargets.Class, AllowMultiple=true, Inherited=false)]
			public class SwizzleAttribute : System.Attribute {

				public Type SourceClass { get; set; }
				public Type TargetClass { get; set; } = null;
				public int NumComponentsToChoose { get; set; } = 0;
				public string[] ComponentsToSwizzle { get; set; }
				
				public SwizzleAttribute() :
					this(null) {}

				public SwizzleAttribute(Type sourceClass, params string[] componentsToSwizzle) :
					this(sourceClass, null, 0, componentsToSwizzle) {}

				public SwizzleAttribute(Type sourceClass, Type targetClass, params string[] componentsToSwizzle) :
					this(sourceClass, targetClass, componentsToSwizzle.Length, componentsToSwizzle) {}
				
				public SwizzleAttribute(Type sourceClass, Type targetClass, int numComponentsToChoose, params string[] componentsToSwizzle) {
					SourceClass = sourceClass;
					TargetClass = targetClass;
					NumComponentsToChoose = numComponentsToChoose;
					ComponentsToSwizzle = componentsToSwizzle;
				}
			}
		}
		""";

	internal static string GetExtensionClassText(TargetExtensionData data) {
		var sb = new StringBuilder();

		var imports = data
			.ClassSwizzleData
			.Values
			.SelectMany(swizzleTargetData =>
				new[] { swizzleTargetData.SourceClassNamespace, swizzleTargetData.TargetClassNamespace }
			)
			.ToImmutableSortedSet();

		sb
			.AppendLine("// <autogenerated/>")
			.AppendLine(string.Join("\n", imports.Select(importNamespace => $"using {importNamespace};")))
			.AppendLine(
				$$"""

				namespace {{data.ExtensionClassNamespace}} {
					public static partial class {{data.ExtensionClassName}} {
					
				"""
			)
			.Append(
				string.Join(
					"\n",
					data.ClassSwizzleData.Values.Select(swizzleTargetData => {
							var instanceSb = new StringBuilder();
							var fields = swizzleTargetData.FieldsToSwizzle.Values;
							var fieldLists = CartesianProduct(fields, swizzleTargetData.NumFieldsToChoose);
							foreach (var fieldList in fieldLists) {
								instanceSb
									.Append($"		public static {swizzleTargetData.TargetClassName} ")
									.Append(string.Join("", fieldList.Select(field => field.Name)))
									.AppendLine($"(this {swizzleTargetData.SourceClassName} source) =>")
									.Append($"			new {swizzleTargetData.TargetClassName}(")
									.Append(string.Join(", ", fieldList.Select(field => $"source.{field.Name}")))
									.AppendLine(");");
							}

							return instanceSb.ToString();
						}
					)
				)
			)
			.AppendLine(
				"""
					}
				}
				"""
			);

		return sb.ToString();
	}

	private static IEnumerable<IList<T>> CartesianProduct<T>(IEnumerable<T> source, int numOfComponents) =>
		CartesianProductInner(source.ToArray(), new T[numOfComponents], numOfComponents, 0);

	private static IEnumerable<IList<T>> CartesianProductInner<T>(T[] ls, T[] nextEntry, int numOfComponents, int i) {
		if (numOfComponents <= i) {
			return [Copy(nextEntry)];
		}
		return ls.SelectMany(t => {
				nextEntry[i] = t;
				return CartesianProductInner(ls, nextEntry, numOfComponents, i + 1);
			}
		);
	}

	private static T[] Copy<T>(T[] ls) {
		var copy = new T[ls.Length];
		ls.CopyTo(copy, 0);
		return copy;
	}
}

internal record struct TargetExtensionData() {
	public string ExtensionClassName { get; set; } = null!;
	public string ExtensionClassNamespace { get; set; } = null!;
	public EqArray<SwizzleTargetData> ClassSwizzleData { get; set; } = null!;
}

internal record struct SwizzleTargetData() {
	public string SourceClassName { get; set; } = null!;
	public string SourceClassNamespace { get; set; } = null!;
	public string TargetClassName { get; set; } = null!;
	public string TargetClassNamespace { get; set; } = null!;
	public int NumFieldsToChoose { get; set; }
	public EqArray<SwizzleFieldData> FieldsToSwizzle { get; set; } = null!;
}

internal record struct SwizzleFieldData() {
	public string Name { get; set; } = null!;
	public string TypeName { get; set; } = null!;
	public string TypeNamespace { get; set; } = null!;
}
