using System.Collections.Immutable;
using System.Text;

namespace DitzyExtensions.Generators;

public class GenUtils {
	public const string SwizzleAttributeFqn = "DitzyExtensions.Generators.SwizzleAttribute";
	public const string GenNamespace = "DitzyExtensions.Generators";

	public const string Swizzle = $$"""
		// <autogenerated/>
		using System;

		namespace {{GenNamespace}} {
			[AttributeUsage(AttributeTargets.Class, AllowMultiple=true, Inherited=false)]
			public class SwizzleAttribute : System.Attribute {

				public Type SourceClass { get; set; }
				public Type TargetClass { get; set; } = null;
				public int NumComponentsToChoose { get; set; } = 0;
				public string[] ComponentsToSwizzle { get; set; }
				
				public SwizzleAttribute() :
					this(null) {}

				public SwizzleAttribute(Type sourceClass, params string[] componentsToSwizzle) :
					this(sourceClass, null, 0, componentsToSwizzle) {}

				public SwizzleAttribute(Type sourceClass, Type targetClass, params string[] componentsToSwizzle) :
					this(sourceClass, targetClass, componentsToSwizzle.Length, componentsToSwizzle) {}
				
				public SwizzleAttribute(Type sourceClass, Type targetClass, int numComponentsToChoose, params string[] componentsToSwizzle) {
					SourceClass = sourceClass;
					TargetClass = targetClass;
					NumComponentsToChoose = numComponentsToChoose;
					ComponentsToSwizzle = componentsToSwizzle;
				}
			}
		}
		""";

	internal static string GetExtensionClassText(TargetExtensionData data) {
		var sb = new StringBuilder();

		var imports = data
			.ClassSwizzleData
			.Values
			.SelectMany(swizzleTargetData =>
				new[] { swizzleTargetData.SourceClassNamespace, swizzleTargetData.TargetClassNamespace }
			)
			.ToImmutableSortedSet();

		sb
			.AppendLine("// <autogenerated/>")
			.AppendLine(string.Join("\n", imports.Select(importNamespace => $"using {importNamespace};")))
			.AppendLine(
				$$"""

				namespace {{data.ExtensionClassNamespace}} {
					public static partial class {{data.ExtensionClassName}} {
					
				"""
			)
			.Append(
				string.Join(
					"\n",
					data.ClassSwizzleData.Values.Select(swizzleTargetData => {
							var instanceSb = new StringBuilder();
							var fields = swizzleTargetData.FieldsToSwizzle.Values;
							var fieldChoices =
								swizzleTargetData.NumFieldsToChoose == 0
									? [fields]
									: Choose(swizzleTargetData.NumFieldsToChoose, fields);
							var fieldLists = fieldChoices.SelectMany(Permute).ToList();
							fieldLists.Sort((a, b) => {
									if (a.Count != b.Count) return a.Count - b.Count;
									return a
										.Select((t, i) => fields.IndexOf(t).CompareTo(fields.IndexOf(b[i])))
										.FirstOrDefault(result => result != 0);
								}
							);
							foreach (var fieldList in fieldLists) {
								instanceSb
									.Append($"		public static {swizzleTargetData.TargetClassName} ")
									.Append(string.Join("", fieldList.Select(field => field.Name)))
									.AppendLine($"(this {swizzleTargetData.SourceClassName} source) =>")
									.Append($"			new {swizzleTargetData.TargetClassName}(")
									.Append(string.Join(", ", fieldList.Select(field => $"source.{field.Name}")))
									.AppendLine(");");
							}

							return instanceSb.ToString();
						}
					)
				)
			)
			.AppendLine(
				"""
					}
				}
				"""
			);

		return sb.ToString();
	}

	private static IEnumerable<IList<T>> Choose<T>(int numToChoose, IList<T> source) {
		var n = source.Count;
		var bitmask = (1 << numToChoose) - 1;
		while (bitmask < (1 << n)) {
			yield return GetChoice(bitmask, source);
			var x = bitmask & -bitmask;
			var y = bitmask + x;
			var z = (bitmask & ~y);
			bitmask = z / x;
			bitmask >>= 1;
			bitmask |= y;
		}
	}

	private static IList<T> GetChoice<T>(int bitmask, IList<T> source) =>
		source.Where((t, i) => IsBitSet(bitmask, i)).ToList();

	private static bool IsBitSet(int bitmask, int index) => ((bitmask >> index) & 1) == 1;

	private static IEnumerable<IList<T>> Permute<T>(IEnumerable<T> source) {
		var ls = source.ToArray();
		var c = new int[ls.Length];

		yield return Copy(ls);

		var i = 1;
		var safetyLimit = Factorial(ls.Length) * 2;
		for (var safety = 0; i < ls.Length && safety < safetyLimit; safety++) {
			if (c[i] < i) {
				if (i % 2 == 0) {
					Swap(ls, 0, i);
				} else {
					Swap(ls, c[i], i);
				}
				yield return Copy(ls);
				c[i] += 1;
				i = 1;
			} else {
				c[i] = 0;
				i += 1;
			}
		}
	}

	private static void Swap<T>(T[] ls, int i, int j) {
		var n = ls.Length - 1;
		(ls[n - i], ls[n - j]) = (ls[n - j], ls[n - i]);
	}

	private static T[] Copy<T>(T[] ls) {
		var copy = new T[ls.Length];
		ls.CopyTo(copy, 0);
		return copy;
	}

	private static int Factorial(int n) {
		var factorial = 1;
		for (; 1 < n; n--) {
			factorial *= n;
		}
		return factorial;
	}
}

internal record struct TargetExtensionData() {
	public string ExtensionClassName { get; set; } = null!;
	public string ExtensionClassNamespace { get; set; } = null!;
	public EqArray<SwizzleTargetData> ClassSwizzleData { get; set; } = null!;
}

internal record struct SwizzleTargetData() {
	public string SourceClassName { get; set; } = null!;
	public string SourceClassNamespace { get; set; } = null!;
	public string TargetClassName { get; set; } = null!;
	public string TargetClassNamespace { get; set; } = null!;
	public int NumFieldsToChoose { get; set; }
	public EqArray<SwizzleFieldData> FieldsToSwizzle { get; set; } = null!;
}

internal record struct SwizzleFieldData() {
	public string Name { get; set; } = null!;
	public string TypeName { get; set; } = null!;
	public string TypeNamespace { get; set; } = null!;
}
