/*
 SPDX-License-Identifier: MIT

 Copyright 2025 ditzy

 Use of this source code is governed by an MIT-style
 license that can be found in the LICENSE file or at
 https://opensource.org/licenses/MIT.
 */

using System.Runtime.InteropServices;
using System.Text;
using DitzyExtensions.Collection;
using DitzyExtensions.Functional;

namespace DitzyExtensions.Testing.Generators;

public static class GenUtils {
	public const string FsCheckOverloadsAttributeFqn = "DitzyExtensions.Testing.Generators.FsCheckOverloadsAttribute";
	public const string GenNamespace = "DitzyExtensions.Testing.Generators";

	public const string FsCheckOverloadsAttribute = $$"""
		// <autogenerated/>
		/*
		 SPDX-License-Identifier: MIT
		 
		 Copyright 2025 ditzy
		 
		 Use of this source code is governed by an MIT-style
		 license that can be found in the LICENSE file or at
		 https://opensource.org/licenses/MIT.
		 */
		 
		using System;

		namespace {{GenNamespace}} {
			[AttributeUsage(AttributeTargets.Class, AllowMultiple=false, Inherited=false)]
			public class FsCheckOverloadsAttribute : System.Attribute {}
		}
		""";

	private const int MaxArgs = 8;

	internal static string GetExtensionClassText(TargetExtensionData data) {
		var sb = new StringBuilder();

		sb
			.AppendLine(
				$$"""
				// <autogenerated/>
				/*
				 SPDX-License-Identifier: MIT
				 
				 Copyright 2025 ditzy
				 
				 Use of this source code is governed by an MIT-style
				 license that can be found in the LICENSE file or at
				 https://opensource.org/licenses/MIT.
				 */
				 
				using System;
				using FsCheck;
				using FsCheck.Fluent;
				
				namespace {{data.ExtensionClassNamespace}} {
					public static partial class {{data.ExtensionClassName}} {
				"""
			)
			.AppendLine(
				SequencedBuild(
					(chars, headChars, lastChar) => {
						var fragA = BuildFrag(chars, c => $"{c.u} {c.l}");
						var fragB = BuildFrag(chars);
						var fragC = BuildFrag(chars, c => $"Gen<{c.u}> {c.l}");
						var fragD = BuildFrag(headChars, c => c.l);
						var fragE = BuildFrag(headChars, c => $"x.{c.l}");
						return
							$$"""
									public static Gen<({{fragA}})> Zip<{{fragB}}>(
										{{fragC}}
									) =>
										Zip({{fragD}}).SelectMany(_ => {{lastChar.l}}, (x, y) => ({{fragE}}, y));
							""";
					},
					minArgs: 3
				)
			)
			.AppendLine()
			.AppendLine(
				SequencedBuild((chars, _, _) => {
						var fragA = BuildFrag(chars, c => $"{c.u} {c.l}");
						var fragB = BuildFrag(chars);
						var fragC = BuildFrag(chars, c => $"Arbitrary<{c.u}> {c.l}");
						var fragD = BuildFrag(chars, c => $"{c.l}.Generator");
						return
							$$"""
									public static Arbitrary<({{fragA}})> Zip<{{fragB}}>(
										{{fragC}}
									) =>
										Arb.From(Zip({{fragD}}));
							""";
					},
					minArgs: 2
				)
			)
			.AppendLine()
			.AppendLine(
				SequencedBuild(
					(chars, _, _) => {
						var fragA = BuildFrag(chars);
						var fragB = BuildFrag(chars, c => $"Arbitrary<{c.u}> {c.l}");
						var fragC = BuildFrag(chars, c => c.l);
						var fragD = BuildFrag(chars, c => $"x.{c.l}");
						return
							$$"""
									public static Property ForAll<{{fragA}}>(
										{{fragB}},
										Action<{{fragA}}> body
									) => Prop.ForAll(Zip({{fragC}}), x => body.Invoke({{fragD}}));
							""";
					},
					minArgs: 2
				)
			)
			.AppendLine(
				"""
					}
				}
				"""
			);

		return sb.ToString();
	}

	private static string SequencedBuild(
		Func<IList<(string u, string l)>, IList<(string u, string l)>, (string u, string l), string> buildFunc,
		int minArgs = 1,
		string separator = "\n"
	) {
		return (minArgs - 1).SequenceTo(MaxArgs)
			.Select(n => {
					var chars = 0.SequenceTo(n + 1)
						.Select(i => Convert.ToChar(i + Convert.ToByte('A')).ToString())
						.Select(c => (u: c, l: c.AsLower()))
						.AsList();
					var headChars = chars.Head(-1).AsList();
					var lastChar = chars.Last();
					return buildFunc(chars, headChars, lastChar);
				}
			)
			.Join(separator);
	}

	private static string BuildFrag(IEnumerable<(string u, string l)> chars, string separator = ", ") =>
		BuildFrag(chars, c => c.u, separator);

	private static string BuildFrag(
		IEnumerable<(string u, string l)> chars,
		Func<(string u, string l), string> fragTransform,
		string separator = ", "
	) =>
		chars.Select(fragTransform).Join(separator);
}

internal record struct TargetExtensionData() {
	public string ExtensionClassName { get; set; } = null!;
	public string ExtensionClassNamespace { get; set; } = null!;
}
