<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Authors>dit-zy</Authors>
		<Title>Ditzy Extensions</Title>
		<Version>2.1.0</Version>
		<Description>a collection of extensions and utilities for making it easier and more convenient to program in a functional style and with collection classes.</Description>
		<RepositoryUrl>https://github.com/dit-zy/ditzy-extensions</RepositoryUrl>
		<TargetFrameworks>net9.0;net8.0;net7.0;net6.0;net48;netstandard2.0</TargetFrameworks>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(TargetFramework)' != 'net48' And '$(TargetFramework)' != 'netstandard2.0' ">
		<Nullable>enable</Nullable>
		<LangVersion>12.0</LangVersion>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(TargetFramework)' == 'net48' Or '$(TargetFramework)' == 'netstandard2.0' ">
		<DefineConstants>N48_S2</DefineConstants>
	</PropertyGroup>

	<ItemGroup Label="dependencies">
		<ProjectReference
			Include="../DitzyExtensions.Generators/DitzyExtensions.Generators.csproj"
			OutputItemType="Analyzer"
			ReferenceOutputAssembly="false"
		/>
		<PackageReference Include="System.Numerics.Vectors" Version="4.6.1" />
		<PackageReference Include="CSharpFunctionalExtensions" Version="3.5.1"/>
	</ItemGroup>

</Project>
