<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<!--
			netcoreapp3.1 is here to test the netstandard2.0 version of ditzy extensions.
			netstandard doesn't include a runtime so cannot be run for testing.
		-->
		<TargetFrameworks>net10.0;net9.0;net8.0;net7.0;net6.0;net48;netcoreapp3.1</TargetFrameworks>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(TargetFramework)' != 'net48' And '$(TargetFramework)' != 'netcoreapp3.1' ">
		<Nullable>enable</Nullable>
		<LangVersion>12.0</LangVersion>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(TargetFramework)' == 'net48' Or '$(TargetFramework)' == 'netcoreapp3.1' ">
		<DefineConstants>N48_S2</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="../DitzyExtensions/DitzyExtensions.csproj"/>
		<ProjectReference Include="../DitzyExtensions.Testing/DitzyExtensions.Testing.csproj"/>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="JetBrains.Annotations" Version="2024.3.0"/>

		<PackageReference Include="FluentAssertions" Version="8.2.0"/>
		<PackageReference Include="FsCheck" Version="3.2.0"/>
		<PackageReference Include="FsCheck.Xunit" Version="3.2.0"/>
		<PackageReference Include="Moq" Version="4.20.72"/>

		<PackageReference Include="coverlet.collector" Version="6.0.4"/>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0"/>
		<PackageReference Include="xunit" Version="2.9.3"/>
		<!-- xunit running has to be this older version to support netcoreapp3.0 -->
		<PackageReference Include="xunit.runner.visualstudio" Version="2.4.0"/>
	</ItemGroup>

</Project>
