//HintName: FsCheckOverloadsAttribute.g.cs
// <autogenerated/>
using System;

namespace DitzyExtensions.Testing.Generators {
	[AttributeUsage(AttributeTargets.Class, AllowMultiple=false, Inherited=false)]
	public class FsCheckOverloadsAttribute : System.Attribute {}
}