//HintName: FsCheckOverloadsAttribute.g.cs
// <autogenerated/>
/*
 SPDX-License-Identifier: MIT
 
 Copyright 2025 ditzy
 
 Use of this source code is governed by an MIT-style
 license that can be found in the LICENSE file or at
 https://opensource.org/licenses/MIT.
 */
 
using System;

namespace DitzyExtensions.Testing.Generators {
	[AttributeUsage(AttributeTargets.Class, AllowMultiple=false, Inherited=false)]
	public class FsCheckOverloadsAttribute : System.Attribute {}
}